version: '3.8'
services:
  apcupsd-exporter:
    image: sfudeus/apcupsd_exporter:latest
    container_name: apcupsd-exporter
    restart: unless-stopped
    ports:
      - 9162:9162
    command: -apcupsd.addr="192.168.1.171:3551"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
volumes:
    prometheus_storage:
    grafana_storage:
